---
- hosts: Ubuntu
  become: true
  tasks: 
  - name: Old installation remove
    file:
      path: /tmp/nagios
      state: absent
    become: true
  - name: Semi-created installation dir get rid
    file:
      path: /tmp/nagios-4.4.5
      state: absent
    become: true
  - name: old installation archive rid
    file:
      path: /tmp/nagios.tar.gz
      state: absent
    become: true
  - name: refresh
    apt: 
      name: '*'
      update_cache: yes
    become: true 
  - name: install nagios required
    apt:
      name: 
        - autoconf
        - gcc
        - libc6
        - make
        - wget
        - unzip
        - libssl-dev
        - apache2
        - php
        - libapache2-mod-php*
        - libgd-dev
        - build-essential
      state: latest
      force: true
      update_cache: true
    become: true
  - name: uncompress and dl
    shell: cd /tmp;rm nagios*.tar.gz;wget -O nagios.tar.gz --no-check-certificate https://assets.nagios.com/downloads/nagioscore/releases/nagios-4.4.5.tar.gz;tar -zxf nagios.tar.gz;mv nagios-4.4.5 nagios
    become: true
  - name: create nagios user
    file:
      path: /home/nagios
      state: directory
      owner: nagios
      group: nagios
      mode: 0775
    become: true
  - name: change home dir and add group member
    command: "{{ item }}"
    with_items: 
      - usermod --home /home/nagios nagios
      - usermod -a -G nagios www-data
    become: true
  - name: create binaries
    command: chdir=/tmp/nagios {{ item }}
    with_items:
      - make install
      - make install-daemoninit 
      - make install-commandmode
      - make install-config
      - make install-webconf
    become: true
  - name: Enable apache2
    apache2_module: state=present name={{ item }}
    with_items:
      - cgi
      - rewrite
  - name: Restart Apache2
    service:
      name: apache2
      state: restarted
    become: true
  - name: nagiosadmin User account
    command: htpasswd -cb /usr/local/nagios/etc/htpasswd.users nagiosadmin nagios
    become: true
  - name: event handlers
    synchronize:
      src: /tmp/nagios/contrib/eventhandlers/
      dest: /usr/local/nagios/libexec
      recursive: yes
      mode: push
    delegate_to: "{{ target_host }}" 
  - name: change ownership and permisions
    file:
      path: /usr/local/nagios/libexec/eventhandlers/
      owner: nagios
      group: nagios
      mode: u+rw,g+rw,o+r
      recurse: true
    become: true
  - name: Start Nagios service
    service:
      name: nagios
      state: restarted
    become: true
